//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int id { get; set; }
        public int idInspector { get; set; }
        public string idDriver { get; set; }
        public string idCar { get; set; }
        public System.DateTime date { get; set; }
        public string area { get; set; }
        public string deprivationLicense { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Inspector Inspector { get; set; }
    }
}
