//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var3
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentsVolations
    {
        public int idIncident { get; set; }
        public int idVolation { get; set; }
        public decimal penalty { get; set; }
        public int statePenalty { get; set; }
    
        public virtual State State { get; set; }
    }
}
